### PR TITLE
Release v3.0.0a3

### PR DESCRIPTION
**Pull request by sphuber**
This version is compatible with `aiida-core==1.0.0b3`.

### CODE REVIEW

**Comment by borellim** [comment]
Can you wait a second? I'll quickly fix #276 and make a PR

**Comment by sphuber** [comment]
Sure. I am going to bed though now. Have a flight to catch early in the morning, but will review and merge tomorrow morning and then rebase and update this PR. So we should be able to make the release tomorrow morning then

**Comment by borellim** [comment]
@sphuber It's easier if you just do it in this PR. Can you just remove [these 3 lines](https://github.com/aiidateam/aiida-quantumespresso/blob/04dcc7bc20f2205d197a2f28b249954c4c01cd4a/aiida_quantumespresso/workflows/pw/band_structure.py#L18...L20)?

**Comment by sphuber** [comment]
No it's fine to do it in a separate PR. Please go ahead and create it, I will merge first thing in the morning and then can update this. I already conferred with Leo and it will be fine if he has the release tomorrow morning

**Comment by borellim** [comment]
Done: #315 
Sorry that I forgot to do it earlier. Thanks a lot.

**Comment by sphuber** [comment]
@borellim tests are failing because I need to adapt same things for compatibility with `1.0.0b3`. I am doing the PR for that first, then will rebase yours and then finally do the release. And don't worry, I forgot about the issue as well!

**Pull request merged**
