### PR TITLE
add pypi deployment to travis

### PR DESCRIPTION
**Pull request by ltalirz**
automatically deploy pypi package when tagging

### CODE REVIEW

**Comment by ltalirz** [comment]
adding this, since I might ask for an a5 release ;-)

**Comment by sphuber** [comment]
I think you copied this more or less from `aiida-core`. Does that mean it will only trigger for tags on the master branch? If so, then this won't help at all for the next alpha correct?

**Comment by ltalirz** [comment]
it should trigger on the tag, independently of the branch

**Comment by sphuber** [comment]
It didn't trigger for `aiida-core==1.0.0b6` though yesterday. Is this different from the `aiida-core` recipe?

**Comment by ltalirz** [comment]
> It didn't trigger for aiida-core==1.0.0b6 though yesterday. Is this different from the aiida-core recipe?

The travis job is still missing from the `develop` branch (only present in `master`).
If you like, I can make a PR to fix this.

**Comment by ltalirz** [comment]
hm wait... it seems I got confused

**Comment by sphuber** [comment]
I don't understand on `aiida-core` in the develop branch I _do_ see the same deploy stage in `.travis.yml` except there we have
```
repo: aiidateam/aiida-core
all_branches: true
tags: true
```
whereas here you do no include `tags`.

**Comment by ltalirz** [comment]
yes, perhaps I looked on my fork - it *is* there, and the deploy job *was* triggered:
https://travis-ci.org/aiidateam/aiida-core/builds/578424816?utm_source=github_status&utm_medium=notification

**Comment by sphuber** [comment]
Ah it seems I already uploaded it manually to PyPI before the deploy stage got the chance. I forgot that this was already up and running even for pre-releases on develop

**Comment by sphuber** [comment]
So final questions, don't we need to include to trigger on `tags` here? And why python 2 and not 3?

**Comment by ltalirz** [comment]
just fixed the tags, happy to switch to py3 as well

**Comment by ltalirz** [comment]
>  I forgot that this was already up and running even for pre-releases on develop

Just updated release instructions as well
https://github.com/aiidateam/aiida-core/wiki/How-to-make-a-new-release

**Comment by sphuber** [comment]
Thanks @ltalirz

**Pull request merged**
