### PR TITLE
Support parsing QE 6.8 outputs

### LINKED ISSUE #713: Support QE 6.8
QE 6.8 has been released, it seems it introduces a new XML schema, here's a diff output of the XML file:
```
< <qes:espresso xsi:schemaLocation="http://www.quantum-espresso.org/ns/qes/qes-1.0 http://www.quantum-espresso.org/ns/qes/qes_030920.xsd" Units="Hartr
ee atomic units" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:qes="http://www.quantum-espresso.org/ns/qes/qes-1.0">
---
> <qes:espresso xsi:schemaLocation="http://www.quantum-espresso.org/ns/qes/qes-1.0 http://www.quantum-espresso.org/ns/qes/qes_210716.xsd" Units="Hartr
ee atomic units" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:qes="http://www.quantum-espresso.org/ns/qes/qes-1.0">
5,7c5,7
<     <xml_format NAME="QEXSD" VERSION="20.04.20">QEXSD_20.04.20</xml_format>
<     <creator NAME="PWSCF" VERSION="6.7MaX">XML file generated by PWSCF</creator>
<     <created DATE=" 4Aug2021" TIME="21:58:47">This run was terminated on:  21:58:47   4 Aug 2021</created>
---
>     <xml_format NAME="QEXSD" VERSION="21.07.16">QEXSD_21.07.16</xml_format>
>     <creator NAME="PWSCF" VERSION="6.8">XML file generated by PWSCF</creator>
>     <created DATE=" 5Aug2021" TIME="17: 6:25">This run was terminated on:  17: 6:25   5 Aug 2021</created>
```

So the parser fails to recognize it
```
Property     Value
-----------  -------------------------------------------------------------
type         PwCalculation
state        Finished [322] The XML output file has an unsupported format.
pk           8243
uuid         591d3809-a35b-48f7-b294-8e2f80d7f802
label
description
ctime        2021-08-05 15:02:17.001271+00:00
mtime        2021-08-05 15:06:29.471525+00:00
computer     [1] localhost
```

### PR DESCRIPTION
**Pull request by qiaojunfeng**
Hi,

This PR adds the XML schema and a test for QE 6.8 output.
Note due to a bug in QE 6.8 output XML, this PR works only after applying this (freshly merged 😅) patch https://gitlab.com/QEF/q-e/-/merge_requests/1531 to QE. 

Fix #713

### CODE REVIEW

**Comment by sphuber** [comment]
Thanks @qiaojunfeng . So does that mean that adding this won't help for people running v6.8 and parsing will fail? If that is the case, I think we should add the schema that works with v6.8 and then add this schema once the fix is released in a patch version of QE. Otherwise it seems to make little sense to me.

**Comment by mbercx** [comment]
Thanks @qiaojunfeng! I did a little test run for a magnetic system, and unfortunately it seems that the output format for the magnetic moments has changed, resulting in the following error:

```
+-> CRITICAL at 2021-09-10 11:54:54.744964+00:00
 | Traceback (most recent call last):
 |   File "/home/aiida/envs/aiida-lumi/code/aiida-quantumespresso/aiida_quantumespresso/parsers/pw.py", line 324, in parse_stdout
 |     parsed_data, logs = parse_stdout(stdout, parameters, parser_options, parsed_xml)
 |   File "/home/aiida/envs/aiida-lumi/code/aiida-quantumespresso/aiida_quantumespresso/parsers/parse_raw/pw.py", line 640, in parse_stdout
 |     line2 = data_step[count + j]
 | IndexError: list index out of range
+-> ERROR at 2021-09-10 11:54:54.747584+00:00
 | The parser raised an unexpected exception.
+-> WARNING at 2021-09-10 11:54:54.749605+00:00
 | output parser returned exit code<350>: The parser raised an unexpected exception.
```

This is the format for the magnetic moments in v6.8:

```
     Magnetic moment per site  (integrated on atomic sphere of radius R)
     atom   1 (R=0.292)  charge=  7.9920  magn= -0.0000
     atom   2 (R=0.292)  charge=  1.2243  magn=  0.0000
```

Compare that to the following example from v6.7:

```
     Magnetic moment per site:
     atom:    1    charge:    0.4485    magn:    0.0000    constr:    0.0000
     atom:    2    charge:    0.4485    magn:    0.0000    constr:    0.0000
     atom:    3    charge:    4.1095    magn:   -0.0000    constr:    0.0000
     atom:    4    charge:    4.1095    magn:   -0.0000    constr:    0.0000
```

This messes up the parsing:

https://github.com/aiidateam/aiida-quantumespresso/blob/c49def7a238617439feb75afd0d0cf9fbb681613/aiida_quantumespresso/parsers/parse_raw/pw.py#L[…]3

Going to check if the magnetic moments are in the XML now. If not, I have a fix somewhere for this when we were doing some test runs on the QE develop branch, will dig that up.

**Comment by mbercx** [comment]
No luck, I'm afraid. I can't seem to find the magnetic moments of each site in the XML. Here's the lines I added to fix this after:

https://github.com/aiidateam/aiida-quantumespresso/blob/c49def7a238617439feb75afd0d0cf9fbb681613/aiida_quantumespresso/parsers/parse_raw/pw.py#L641-L643

```
                        elif 'atom' in line2:
                            mag_moments.append(float(line2.split('magn=')[1].split()[0]))
                            charges.append(float(line2.split('charge=')[1].split()[0]))
```

Will try to do this in my branch on thanos and see if the magnetic moments are parsed properly.

**Comment by giovannipizzi** [comment]
Thanks @mbercx!
It would be great to inform Pietro Delugas
1. about this change
2. about the fact that this information is not in the XML
so maybe they manage to put this in for the next version(s).

Can you ping him please?

**Comment by sphuber** [comment]
@mbercx I guess what you are describing is more or less a separate problem is it not? Shall we already merge this, and then I let you open a PR to fix the parsing of magnetic moments from the stdout?

**Comment by mbercx** [comment]
@sphuber sure, that'd work as well. 👍 Just figured it would fit in the topic of this PR, but I wouldn't want to introduce scope creep for @qiaojunfeng!

@giovannipizzi Sure! Will open a new issue an ping him there.

**Review by sphuber — APPROVED** [review]
Thanks a lot @qiaojunfeng

**Pull request merged**
