### PR TITLE
Handle parsing of stdout when atomic positions have `crystal` units

### PR DESCRIPTION
**Pull request by chrisjsewell**
@sphuber liking the parser improvements :)

This is principally for use with immigrating existing runs (see aiidateam/aiida-quantumespresso#337).
As outlined in the commit message, when input atomic positions have been defined using `ATOMIC_POSITIONS crystal`. This necessitates a conversion from fractional to cartesian positions, for the trajectory positions. I reckon my solution, using `numpy.einsum`, is pretty nice!

Additionally:
- added a file to the `tests/parsers/fixtures/pw/failed_missing folder` (otherwise it isn't added to git)
- added a fix for retrieving symbols structure symbols, when the `kind_names` are different to the actual element symbol
- added a `generate_inputs_vcrelax` fixture, and a test for this use case.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
I'm sure you know, but the tests failing are due to aiidateam/aiida_core#2960

**Comment by sphuber** [comment]
Thanks Chris, I will give a look later and yes you are right, they are failing for that reason. I should be releasing the next beta early next week, after which we can update the dependency and tests should start running again

**Comment by chrisjsewell** [comment]
Sounds good ta. Do you reckon there's much more to do on this branch? It looks to be pretty much complete to me.

**Comment by sphuber** [comment]
Not sure, I am testing this currently in a high-throughput project I am running and there are a few more fixes I have to do. Then I would really like to simplify clean some things, but those would be backwards incompatible. Like for example, I want to get rid of the `output_` prefix in output node link labels. But I need to discuss this with Gio.

**Comment by chrisjsewell** [comment]
@sphuber I sorted all those weird merge conflicts btw

**Comment by sphuber** [comment]
> Don't know how you handle these, but using GitHub Desktop with the [VS Code merge conflicts functionality](https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts), has made it so much easier for me.

I do it "manually" just using Sublime + git. Your method doesn't really seems to have worked though as there are now 25 commits, many of which are duplicates. Anyway, I just merged `3dd` into `develop` so I think it is best to close this. If you still want to incorporate these changes, please open a new clean PR. Sorry about the bother

**Comment by chrisjsewell** [comment]
Hmm, it normal work, anyway no worries, re-done in #368

**Pull request closed without merging**
