### PR TITLE
Release `v4.4.0`

### PR DESCRIPTION
**Pull request by mbercx**

### CODE REVIEW

**Comment by mbercx** [comment]
@sphuber would be good to do the release soon, since CI pipelines downstream are failing due to the `pydantic` bug.

**Comment by sphuber** [comment]
Sure, I was just waiting for a reply to this comment: https://github.com/aiidateam/aiida-quantumespresso/pull/756#issuecomment-1575544808
i.e. did you want to merge that parse refactor before the release?

**Comment by mbercx** [comment]
> Sure, I was just waiting for a reply to this comment: [#756 (comment)](https://github.com/aiidateam/aiida-quantumespresso/pull/756#issuecomment-1575544808) i.e. did you want to merge that parse refactor before the release?

I see! I missed that comment. It would be nice to get #756 merged for sure, #640 as well. For the latter I've added a full tutorial, as well as a new tool for passing magnetic configurations that I rather like. Maybe you can have a closer look at reviewing the final changes in #640, and I'll look at #756 to see if there is anything critical and open an issue for leftover points so we don't lose track of them.

**Comment by mbercx** [comment]
@sphuber I think all features we wanted to include in the release are now merged, so I updated the PR. Ready for review!

**Review by sphuber — APPROVED** [review]
Good to go, thanks @mbercx

**Pull request merged**
