### PR TITLE
`PwBaseWorkChain`: add handler for `ERROR_COMPUTING_CHOLESKY`

### LINKED ISSUE #213: `PwBaseWorkChain`: implement handler for cholesky decomposition problems
A `pw.x` calculation can throw the following error:
```
     Davidson diagonalization with overlap

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine  cdiaghg (668):
      problems computing cholesky
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...
```

from which the base workchain cannot recover and restarting is pointless. There should therefore be an error handler that exits the work chain with an appropriate exit code.

### PR DESCRIPTION
**Pull request by sphuber**
Fixes #213 

Currently there is no known cure for this problem so a handler is added
to abort the workchain.

### CODE REVIEW

**Comment by greschd** [comment]
@sphuber from [this forum post](https://www.mail-archive.com/users@lists.quantum-espresso.org/msg32363.html), it seems at least sometimes the problem is fixed by setting `-ndiag 1`.

I've encountered at least one instance where that is also the case. Absent any better options, should we implement this handler - even if it could hurt performance?

Implementing this would be easier after https://github.com/aiidateam/aiida-quantumespresso/issues/405 is done - so maybe that's something to put higher on my priority list.

**Comment by sphuber** [comment]
That is of course if the `-ndiag` is explicitly set to anything other than 1, because the default is 1, right?

**Comment by greschd** [comment]
Ha, that's what I thought also! But actually it's (from [here](https://www.quantum-espresso.org/Doc/user_guide/node20.html))

> nd is set to 1 if ScaLAPACK is not compiled, it is set to the square integer smaller than or equal to half the number of processors of each pool

I was confused initially because I had _not_ set `ndiag` explicitly.

**Comment by sphuber** [comment]
> I guess detecting whether ScaLAPACK is compiled is not really something we can do .. right? joy

Regardless of whether we could, I am not opening that can of worms :)

**Comment by greschd** [comment]
Just to document some observations I've made:

> nd is set to 1 if ScaLAPACK is not compiled, it is set to the square integer smaller than or equal to half the number of processors of each pool

This is actually incorrect; as of [this QE MR](https://gitlab.com/QEF/q-e/-/merge_requests/626) the default goes up the the _full_ number of processors. [MR to fix the documentation](https://gitlab.com/QEF/q-e/-/merge_requests/1179) is filed.

Maybe a more interesting observation is that it's not always necessary to set `ndiag` to `1` to fix the Cholesky error - just reducing it can also solve it. I'm not sure if there's a good rule for how much `ndiag` is too much, though. In terms of adding a handler, maybe just switching to `1` is the safer option (I don't know _how much_ performance is expected to degrade due to that).

**Pull request merged**
