### PR TITLE
✨ Add the XML schema for Quantum ESPRESSO v7.3.1 `pw.x`

### PR DESCRIPTION
**Pull request by mbercx**

### CODE REVIEW

**Comment by mbercx** [comment]
@npaulish could you give this a spin for a small test system and send me the files? :))

**Comment by mbercx** [comment]
@Minotakm I've added you to the repo as a collaborator. Once you accept, you can review this PR so you understand how to add support for new QE versions.

**Review by Minotakm — COMMENTED** [review]
Hey @mbercx and @npaulish thanks for the changes :smile:  . Is it possible to add the aiida.out and the data-file-schema.xml on the tests/parsers/fixtures/pw folder in a new folder called default_xml_<schema_date> ?

**Review by Minotakm — APPROVED** [review]
I think that now everything is fine. Thanks @mbercx :smile:

**Comment by mbercx** [comment]
Almost, forgot to regenerate `pytest` regression file to latest (more compact) test files.

**Comment by mbercx** [comment]
Ok, fully ready for review now 👍

**Review by Minotakm — APPROVED** [review]
Seems that everything is alright. Thanks @mbercx

**Comment by rikigigi** [comment]
This works also for me, is it ready to be merged?

**Comment by mbercx** [comment]
Apologies @rikigigi, seems we forgot to finalise this in the end. Let me rebase and get it merged!

**Comment by rikigigi** [comment]
thank you! :-)

**Pull request merged**
