### PR TITLE
Fix documentation (+ add tox configuration)

### PR DESCRIPTION
**Pull request by chrisjsewell**
The documentation CLI is not set up correctly, which has "hidden" a multitude of issues in the documentation build

### CODE REVIEW

**Comment by chrisjsewell** [comment]
FYI the docs are building with a bunch of warnings: https://readthedocs.org/projects/aiida-quantumespresso/builds/12867318/

**Comment by chrisjsewell** [comment]
@sphuber can you add me as a maintainer for the readthedocs: https://readthedocs.org/projects/aiida-quantumespresso/ (my username is cjsewell). The current maintainer is an `aiida` profile, do you have the login details for that?

**Comment by chrisjsewell** [comment]
https://github.com/aiidateam/aiida-tcod is not available on PyPi, and so the `tcod` extra does not work (and so autodoc fails for `docs/source/module_guide/tcod_dbexporter.rst`).
Given this, I assume also that the `aiida_quantumespresso/tools/dbexporters/tcod_plugins` code is not at all tested.

aiida-tcod has not been updated for two years, so I think this code should just be removed and the repo archived (cc also @ltalirz who was the last to commit to that repo)

**Comment by ltalirz** [comment]
@chrisjsewell I only merged a PR to aiida-tcod - aiida-tcod was handled by @sphuber

**Comment by chrisjsewell** [comment]
I assume you are no longer using it though?

**Comment by chrisjsewell** [comment]
Next issue: the `docs/source/devel_guide/workchains.rst` is completely out of date, since the `BaseRestartWorkChain` has been moved to to aiida-core.
We should remove most of this page; linking to the relevant documentation in aiida-core and only mentioning information specific to aiida-quantumespresso.

https://github.com/aiidateam/aiida-core/pull/4562 is opened by @mbercx to fix https://github.com/aiidateam/aiida-core/issues/3993, but I don't yet see any documentation specific to `BaseRestartWorkChain`?

**Comment by chrisjsewell** [comment]
Finally, there is a bunch of references, that presumably been renamed, removed or moved to aiida-core:

```
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/cp_tutorial.rst:145: WARNING: undefined label: my-ref-to-pseudo-tutorial
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/ph_tutorial.rst:89: WARNING: undefined label: my-reference-to-scheduler
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/pw_tutorial.rst:129: WARNING: undefined label: working_calculations
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/pw_tutorial.rst:129: WARNING: undefined label: concepts_processes
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/pw_tutorial.rst:192: WARNING: undefined label: structure_tutorial
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/pw_tutorial.rst:235: WARNING: undefined label: my-ref-to-structure
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/pw_tutorial.rst:249: WARNING: undefined label: structure_tutorial
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/pw_tutorial.rst:562: WARNING: undefined label: my-ref-to-pseudo-tutorial
/Users/chrisjsewell/Documents/GitHub/aiida-quantumespresso-develop/docs/source/user_guide/get_started/examples/pw_tutorial.rst:648: WARNING: undefined label: working_processes_launching
```

**Comment by ltalirz** [comment]
> I assume you are no longer using the plugin though?

I've never used it. I suggest to let @sphuber or @giovannipizzi to about the fate of this code

**Comment by chrisjsewell** [comment]
> I've never used it. I suggest to let @sphuber or @giovannipizzi decide about the fate of this code

I have moved this to a separate issue #644

**Comment by chrisjsewell** [comment]
ok ready for review

**Review by mbercx — APPROVED** [review]
Thanks @chrisjsewell!

**Pull request merged**
