### PR TITLE
[WIP] Closes #243 migrate cp calculation

### LINKED ISSUE #243: Migrate `CpCalculation` to be compatible with `aiida-core==1.0.0`

### PR DESCRIPTION
**Pull request by odarbelaeze**
The idea here is to migrate the good old cp calculation to aiida 1.0

Link to my dev environment: https://github.com/odarbelaeze/aiida-qe-docker-dev

### CODE REVIEW

**Comment by borellim** [comment]
Hi Oscar. I have a couple of comments.

* Could you try to separate meaningful changes from large-scale style refactoring? The first commit has 2 meaningful changes, if I'm correct: one in calculations/__init__.py, and one in setup.json; the rest is style.
* If you make changes that impact a single calculation or parser plugin, could you try to specify it in the commit message (e.g.: "cp: start the define process").

Thanks a lot!

**Comment by odarbelaeze** [comment]
@borellim I was looking at the whole set of changes, and if I just recover that `__init__` file and make only the meaningful changes it'll be ok, right?

**Comment by borellim** [comment]
You also upgraded the aiida-core dependency in setup.json, if you want you can also add that change in the same commit. The rest of the changes should go in a separate commit, yes.

**Comment by odarbelaeze** [comment]
I'm closing this one and reproducing the work in a "cleaner" way in another branch. Apologies for the delay here @borellim @sphuber

**Pull request closed without merging**
