### PR TITLE
Closes 245 migrate pp calculation

### PR DESCRIPTION
**Pull request by odarbelaeze**
I'm missing an example and a test, probably the test will be irrelevant now since there's no parser for this code.

### CODE REVIEW

**Comment by odarbelaeze** [comment]
@sphuber mind to overtake this one PR, it's missing the example cli.

**Comment by sphuber** [comment]
> @sphuber mind to overtake this one PR, it's missing the example cli.

Sure no problem. I am currently addressing #289 so it makes sense to address it after that is merged

**Comment by odarbelaeze** [comment]
@sphuber how confident do you feel about this one being done? do you think I should debase it, get it ready and press the merge button?

**Comment by sphuber** [comment]
@odarbelaeze I'm happy with the state. I merely added some stylistic changes. Feel free to squash my changes in your commit, rebase to update it and then merge it

**Comment by odarbelaeze** [comment]
@sphuber lol, can't do, it would need an approved from someone who's not "the author", could I get it?

**Comment by odarbelaeze** [comment]
Feels like team work :shipit:

**Pull request merged**
